Repository chainer/chainermn, pull requests merged in 2018-05, with the labels that each got.

#237 Add allreduce method to communicator interface with implementation
  chainermn/communicators/communicator_base.py
  chainermn/communicators/mpi_communicator_base.py
  tests/chainermn_tests/communicator_tests/test_communicator.py
Labels: feature

#257 Remove unused nccl comm and mpi comm
  chainermn/communicators/_communication_utility.py
  chainermn/communicators/dummy_communicator.py
  chainermn/communicators/flat_communicator.py
  chainermn/communicators/hierarchical_communicator.py
  chainermn/communicators/mpi_communicator_base.py
  chainermn/communicators/non_cuda_aware_communicator.py
  chainermn/communicators/pure_nccl_communicator.py
  chainermn/communicators/single_node_communicator.py
  chainermn/communicators/two_dimensional_communicator.py
  tests/chainermn_tests/communicator_tests/test_communicator.py
  tests/chainermn_tests/communicator_tests/test_node_aware_communicator_base.py
  tests/chainermn_tests/optimizer_tests/test_double_buffering_optimizer.py
Labels: enhancement

#249 Added an FAQ entry about MPI hang issue.
  docs/source/tutorial/tips_faqs.rst
Labels: document

#263 Expose intra- and inter- rank and size
  chainermn/communicators/communicator_base.py
  chainermn/communicators/mpi_communicator_base.py
  docs/source/reference/index.rst
Labels: document, feature

#264 Add note on checkpoints and fix broken autofunction
  chainermn/extensions/checkpoint.py
  docs/source/reference/index.rst
Labels: document
